export const defaultClasses = [
  'h-12',
  'appearance-none',
  'border-none',
  'w-full',
  'py-2.5',
  'px-4',
  'text-black-500',
  'focus:outline-none',
  'focus:border-none',
  'focus:shadow-none',
  'disabled:cursor-not-allowed',
  'disabled:bg-grey-100',
  'text-4xl',
]
